/*
 * This file was automatically generated by EvoSuite
 * Thu May 02 10:42:18 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.charset.Charset;
import java.time.Clock;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.chrono.ThaiBuddhistDate;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockThaiBuddhistDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GestorEncomendas_ESTest extends GestorEncomendas_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      LinkedHashSet<Long> linkedHashSet0 = new LinkedHashSet<Long>();
      Long long0 = new Long(1L);
      linkedHashSet0.add(long0);
      Set<String> set0 = gestorEncomendas0.encomendasToArtigos(linkedHashSet0);
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      LinkedHashSet<Long> linkedHashSet0 = new LinkedHashSet<Long>();
      Set<String> set0 = gestorEncomendas0.encomendasToArtigos(linkedHashSet0);
      Dimensao dimensao0 = Dimensao.Pequeno;
      LocalDate localDate0 = MockLocalDate.now();
      Encomenda encomenda0 = new Encomenda(set0, (-615L), dimensao0, localDate0);
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      int int0 = gestorEncomendas0.tamanhoEncomenda(1L);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      Dimensao dimensao0 = Dimensao.Medio;
      ThaiBuddhistDate thaiBuddhistDate0 = MockThaiBuddhistDate.now();
      LocalDate localDate0 = MockLocalDate.from(thaiBuddhistDate0);
      Encomenda encomenda0 = new Encomenda(set0, (-1L), dimensao0, localDate0);
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      Encomenda encomenda1 = gestorEncomendas0.getEncomenda(1L);
      assertEquals(Dimensao.Grande, encomenda1.getDimensao());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      Encomenda.setDiasDevolver((-5));
      Encomenda encomenda1 = gestorEncomendas0.getEncomenda(1L);
      assertEquals(0, encomenda1.numeroArtigos());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      LinkedHashSet<Long> linkedHashSet0 = new LinkedHashSet<Long>();
      Long long0 = new Long(1L);
      linkedHashSet0.add(long0);
      String string0 = gestorEncomendas0.encomendasToString(linkedHashSet0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Encomenda encomenda0 = new Encomenda();
      encomenda0.setId(0L);
      long long0 = gestorEncomendas0.adicionaEncomenda(encomenda0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Encomenda encomenda0 = new Encomenda();
      encomenda0.setId((-18L));
      long long0 = gestorEncomendas0.adicionaEncomenda(encomenda0);
      assertEquals((-18L), long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      Dimensao dimensao0 = Dimensao.Medio;
      ThaiBuddhistDate thaiBuddhistDate0 = MockThaiBuddhistDate.now();
      LocalDate localDate0 = MockLocalDate.from(thaiBuddhistDate0);
      Encomenda encomenda0 = new Encomenda(set0, (-1L), dimensao0, localDate0);
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      int int0 = gestorEncomendas0.EncomendaToQuantidade(1L);
      assertEquals(603, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Encomenda encomenda0 = new Encomenda();
      Charset charset0 = Charset.defaultCharset();
      Set<String> set0 = charset0.aliases();
      encomenda0.setEncomenda(set0);
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      gestorEncomendas0.removeEncomenda(1L);
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      Set<String> set1 = gestorEncomendas0.EncomendaToArtigos(1L);
      assertFalse(set1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      // Undeclared exception!
      try { 
        gestorEncomendas0.setEncomendas((Map<Long, Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      // Undeclared exception!
      try { 
        gestorEncomendas0.adicionaEncomenda((Encomenda) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = null;
      try {
        gestorEncomendas0 = new GestorEncomendas((Map<Long, Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = null;
      try {
        gestorEncomendas0 = new GestorEncomendas((GestorEncomendas) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      try { 
        gestorEncomendas0.getEncomenda(454L);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existe nehuma encomenda com o ID 454
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      try { 
        gestorEncomendas0.FinalizadaToExpedida((-1079L), localDate0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // A encomenda com o ID -1079n\u00E3o foi expedida
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      LinkedHashSet<Long> linkedHashSet0 = new LinkedHashSet<Long>();
      Long long0 = new Long(1L);
      linkedHashSet0.add(long0);
      // Undeclared exception!
      try { 
        gestorEncomendas0.encomendasToString(linkedHashSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      LinkedHashSet<Long> linkedHashSet0 = new LinkedHashSet<Long>();
      String string0 = gestorEncomendas0.encomendasToString(linkedHashSet0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      String string0 = gestorEncomendas0.encomendaToString(1L);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      try { 
        gestorEncomendas0.encomendaToString(0L);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o exite nenhuma encomenda com o ID 0
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      Dimensao dimensao0 = Dimensao.Medio;
      ThaiBuddhistDate thaiBuddhistDate0 = MockThaiBuddhistDate.now();
      LocalDate localDate0 = MockLocalDate.from(thaiBuddhistDate0);
      Encomenda encomenda0 = new Encomenda(set0, (-1L), dimensao0, localDate0);
      Encomenda encomenda1 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda1);
      int int0 = gestorEncomendas0.EncomendaToQuantidade(2L);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      try { 
        gestorEncomendas0.EncomendaToQuantidade(1L);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o exite nenhuma encomenda com o ID 1
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      gestorEncomendas0.removeEncomenda(1L);
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      Set<String> set0 = gestorEncomendas0.EncomendaToArtigos(1L);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      try { 
        gestorEncomendas0.EncomendaToArtigos(1L);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o exite nenhuma encomenda com o ID 1
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      LinkedHashSet<Long> linkedHashSet0 = new LinkedHashSet<Long>();
      Long long0 = new Long(1L);
      linkedHashSet0.add(long0);
      // Undeclared exception!
      try { 
        gestorEncomendas0.encomendasToArtigos(linkedHashSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      // Undeclared exception!
      try { 
        gestorEncomendas0.podeDevolvida(1L, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.time.temporal.ChronoUnit", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      try { 
        gestorEncomendas0.podeDevolvida((-242L), (LocalDate) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o exite nenhuma encomenda com o ID -242
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      gestorEncomendas0.removeEncomenda(1L);
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      gestorEncomendas0.FinalizadaToExpedida(1L, localDate0);
      Set<String> set0 = gestorEncomendas0.podeDevolvida(1L, localDate0);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      try { 
        gestorEncomendas0.removeEncomenda((-2029L));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o exite nenhuma encomenda com o ID -2029
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      try { 
        gestorEncomendas0.adicionaEncomenda(encomenda0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe uma encomenda com o ID 1
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      GestorEncomendas gestorEncomendas1 = new GestorEncomendas(gestorEncomendas0);
      boolean boolean0 = gestorEncomendas1.equals(gestorEncomendas0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      boolean boolean0 = gestorEncomendas0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      boolean boolean0 = gestorEncomendas0.equals(gestorEncomendas0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Integer integer0 = new Integer(0);
      boolean boolean0 = gestorEncomendas0.equals(integer0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      Map<Long, Encomenda> map0 = gestorEncomendas0.getEncomendas();
      gestorEncomendas0.setEncomendas(map0);
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Map<Long, Encomenda> map0 = gestorEncomendas0.getEncomendas();
      gestorEncomendas0.setEncomendas(map0);
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Encomenda encomenda0 = new Encomenda();
      gestorEncomendas0.adicionaEncomenda(encomenda0);
      Map<Long, Encomenda> map0 = gestorEncomendas0.getEncomendas();
      GestorEncomendas gestorEncomendas1 = new GestorEncomendas(map0);
      assertFalse(gestorEncomendas1.equals((Object)gestorEncomendas0));
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      String string0 = gestorEncomendas0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      // Undeclared exception!
      try { 
        gestorEncomendas0.tamanhoEncomenda(0L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GestorEncomendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      GestorEncomendas gestorEncomendas1 = gestorEncomendas0.clone();
      assertNotSame(gestorEncomendas1, gestorEncomendas0);
  }
}
