/*
 * This file was automatically generated by EvoSuite
 * Thu May 02 10:49:55 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Month;
import java.time.ZoneId;
import java.time.ZoneOffset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Mala_ESTest extends Mala_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      mala0.setValorizacao((-1749.1F));
      mala1.getValorizacao();
      mala1.isPremium();
      mala0.setValorizacao(2L);
      mala1.equals(mala0);
      mala1.toString();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1988L));
      mala1.equals(localDate0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setDimensao(12);
      mala0.setVendedor(12);
      mala0.setPremium(false);
      mala0.setPremium(false);
      LocalDate localDate0 = MockLocalDate.now();
      mala0.preco_atual(localDate0);
      Mala mala1 = new Mala(mala0);
      mala0.equals(mala1);
      mala1.setPremium(false);
      LocalDate localDate1 = MockLocalDate.from(localDate0);
      mala1.preco_atual(localDate1);
      mala1.setDisponivel(false);
      mala1.setDimensao(0);
      mala0.setPremium(true);
      mala0.setValorizacao(2L);
      mala0.getMaterial();
      mala0.isPremium();
      mala0.equals(mala1);
      mala0.toString();
      mala0.toString();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      System.setCurrentTimeMillis(0L);
      Mala mala0 = new Mala();
      Object object0 = new Object();
      mala0.equals(object0);
      mala0.setMaterial("1X({,BEL%M'oM /");
      Mala mala1 = mala0.clone();
      Mala mala2 = mala0.clone();
      mala0.setDisponivel(false);
      mala2.setData_venda((LocalDate) null);
      mala0.toString();
      mala1.setDimensao((-163));
      System.setCurrentTimeMillis(334L);
      Mala mala3 = mala0.clone();
      Mala mala4 = mala0.clone();
      mala4.mostrar((LocalDate) null);
      mala4.setData_venda((LocalDate) null);
      Artigo.codigo = "A";
      int int0 = 28;
      mala4.setN_utilizadores(28);
      System.setCurrentTimeMillis(2L);
      Object object1 = new Object();
      mala1.equals(object1);
      mala3.preco_atual((LocalDate) null);
      mala4.preco_atual((LocalDate) null);
      // Undeclared exception!
      try { 
        mala4.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setDimensao((-1));
      mala0.setVendedor((-1));
      mala0.isPremium();
      mala0.setPremium(false);
      mala0.setPremium(false);
      LocalDate localDate0 = MockLocalDate.now();
      mala0.preco_atual(localDate0);
      mala0.setDimensao(0);
      Mala mala1 = new Mala(mala0);
      mala0.equals(mala1);
      mala1.setPremium(false);
      LocalDate localDate1 = MockLocalDate.from(localDate0);
      mala1.preco_atual(localDate1);
      mala1.setDisponivel(false);
      mala1.setDimensao(0);
      mala0.setPremium(true);
      mala0.setValorizacao(2L);
      mala0.getMaterial();
      mala0.isPremium();
      mala0.equals(mala1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      mala1.setAno_colecao((-1));
      mala1.equals(mala0);
      mala1.mostrar((LocalDate) null);
      mala0.setNovo(true);
      mala0.setCodigo_barras("Mek");
      mala1.setDisponivel(true);
      mala0.setAno_colecao(976);
      mala1.setDimensao(1805);
      Mala mala2 = mala0.clone();
      mala0.setN_utilizadores(2725);
      mala2.getValorizacao();
      mala2.setMaterial("sMn;9:D,6_;ME?P2j");
      mala2.toString();
      mala1.getMaterial();
      mala2.preco_atual((LocalDate) null);
      mala0.setMaterial("Mala:: {Artigo:: { C\u00F3digo de barras: Mek Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: true Estado de uso: -1 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Dimens\u00E3o: 0 Material: sMn;9:D,6_;ME?P2j Ano da Cole\u00E7\u00E3o: 976 Premium: false Valoriza\u00E7\u00E3o: 0.0}");
      mala0.setPremium(false);
      Object object0 = new Object();
      mala2.equals(object0);
      mala1.clone();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.equals(mala0);
      mala0.setCodigo_barras("A");
      mala0.setMaterial("A");
      Artigo.setCodigo("4");
      mala0.setPremium(false);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setDimensao(828);
      Mala mala1 = new Mala(mala0);
      mala1.toString();
      Artigo.setCodigo((String) null);
      Artigo.contador = 0L;
      mala1.setMaterial((String) null);
      mala1.preco_atual((LocalDate) null);
      mala0.setAno_colecao((-575));
      mala1.getValorizacao();
      mala1.setAno_colecao((-575));
      mala1.setTransportadora(0L);
      mala0.setValorizacao(0.0F);
      mala1.setValorizacao(0.0F);
      mala1.preco_atual((LocalDate) null);
      mala1.setDimensao((-575));
      mala0.setAno_colecao((-575));
      mala1.setAno_colecao(828);
      Mala mala2 = mala1.clone();
      mala0.preco_atual((LocalDate) null);
      Mala mala3 = mala0.clone();
      mala0.setValorizacao(0L);
      mala3.setMaterial("");
      mala2.getValorizacao();
      mala2.clone();
      mala3.getValorizacao();
      mala0.isPremium();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      mala1.getAno_colecao();
      Artigo.setContador(0);
      Artigo.contador = 0L;
      Artigo.contador = 1L;
      mala1.getMaterial();
      Mala mala2 = mala1.clone();
      Artigo.setCodigo("");
      Mala mala3 = mala2.clone();
      mala3.setTransportadora(1L);
      mala2.setDescricao("SO|!jO]4jC(?N<E");
      Artigo.contador = (-738L);
      Mala mala4 = mala3.clone();
      mala4.setPremium(true);
      Mala mala5 = mala4.clone();
      mala5.setMaterial("Artigo:: {");
      mala3.setValorizacao((-738L));
      mala3.getValorizacao();
      LocalDate localDate0 = mala2.getData_venda();
      mala1.preco_atual(localDate0);
      mala0.setMaterial("");
      mala3.setAno_colecao(847);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Mala mala0 = new Mala();
      Artigo.contador = 2L;
      mala0.setPremium(true);
      mala0.isPremium();
      int int0 = (-2393);
      LocalDate localDate0 = null;
      // Undeclared exception!
      try { 
        mala0.preco_atual((LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Mala", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setVendedor(1L);
      mala0.setEstado_uso(2193);
      mala0.getDimensao();
      mala0.setDimensao(2825);
      mala0.setDimensao((-15));
      mala0.setValorizacao(2825);
      mala0.setAno_colecao(0);
      Mala mala1 = mala0.clone();
      mala0.setDimensao(2825);
      mala1.setAno_colecao((-1));
      mala0.getValorizacao();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Double double0 = new Double((-2074.76));
      Long long0 = new Long(2377L);
      Mala mala0 = new Mala("T#yH%' fHt,", " Marca: ", double0, true, (-3697), (-3697), long0, long0, 0, " Marca: ", (-3697), true, (-3697));
      Double.max(0, 2377L);
      Long.getLong(" Marca: ", 0L);
      Artigo.contador = (-2862L);
      mala0.setDisponivel(true);
      mala0.getMaterial();
      mala0.getMaterial();
      mala0.setAno_colecao(0);
      mala0.setMaterial("");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      mala1.setVendedor(0L);
      Mala mala2 = mala1.clone();
      mala0.setDisponivel(false);
      mala2.setPreco_base(1.0);
      mala1.setPreco_base(0.01);
      Artigo.setCodigo("A");
      mala2.setEstado_uso((-1269));
      mala0.clone();
      mala0.setPremium(false);
      System.setCurrentTimeMillis((-262L));
      System.setCurrentTimeMillis(2L);
      Object object0 = new Object();
      mala1.equals(object0);
      Month month0 = Month.FEBRUARY;
      // Undeclared exception!
      try { 
        MockLocalDate.of(4, month0, 4909);
        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid value for DayOfMonth (valid values 1 - 28/31): 4909
         //
         verifyException("java.time.temporal.ValueRange", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Mala mala0 = null;
      try {
        mala0 = new Mala((Mala) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Double double0 = new Double(1.0);
      Double.isFinite(1.0);
      Double.min(1.0, 3731L);
      Long long0 = new Long(3731L);
      Mala mala0 = new Mala(" Premium: ", "", double0, false, 0, 0, long0, long0, 1, "", 0, false, (-53.044F));
      Long.compareUnsigned(0L, (-1533L));
      mala0.setValorizacao(3731L);
      mala0.getAno_colecao();
      mala0.getAno_colecao();
      Mala mala1 = mala0.clone();
      mala1.setPremium(false);
      mala1.getValorizacao();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Double double0 = new Double(760.3);
      Double.min(0.0, (-875.0));
      Long long0 = new Long(0L);
      Mala mala0 = new Mala("X", (String) null, double0, true, 3866, 2537, long0, long0, 3866, (String) null, (-227), true, (-1098.58F));
      mala0.setValorizacao((-1098.58F));
      mala0.equals("1|^N");
      mala0.getMaterial();
      mala0.getAno_colecao();
      mala0.setValorizacao(3866);
      mala0.setAno_colecao((-227));
      Long.remainderUnsigned(1L, (-227));
      mala0.setPremium(true);
      mala0.equals("1|^N");
      mala0.setAno_colecao((-1));
      mala0.setValorizacao(1L);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setPreco_base((-1122.1578393));
      Mala mala1 = new Mala();
      mala1.setMaterial("mX-7MpE]Fi!");
      mala0.isPremium();
      mala1.setDisponivel(false);
      mala0.setValorizacao((-1749.1F));
      mala1.getValorizacao();
      mala1.isPremium();
      mala1.equals(mala0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Double double0 = new Double(0.0);
      Long long0 = new Long((-3644L));
      Long long1 = new Long((-3467L));
      Mala mala0 = new Mala("", "", double0, false, (-1050), 10, long0, long1, 10, " Descri\u00E7\u00E3o: ", (-1050), true, (-3644L));
      mala0.setMaterial("mX-7MpE]Fi!");
      mala0.setMarca(":b:dBn-TQ1g|T");
      mala0.getDimensao();
      mala0.getAno_colecao();
      mala0.setAno_colecao((-2778));
      mala0.clone();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.toString();
      mala0.getDimensao();
      mala0.setValorizacao(977.21F);
      Mala mala1 = mala0.clone();
      Mala mala2 = mala1.clone();
      mala2.setEstado_uso(1585);
      mala0.setPremium(true);
      mala2.getAno_colecao();
      mala0.setMaterial("A");
      mala0.setDimensao(0);
      mala1.clone();
      mala1.getValorizacao();
      mala2.getValorizacao();
      mala1.toString();
      mala0.equals(" Dimens\u00E3o: ");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Double double0 = new Double(0.0);
      Long long0 = new Long(1343L);
      Long long1 = Long.valueOf((long) 0);
      Mala mala0 = new Mala("q0no\"MvX", "q0no\"MvX", double0, true, 0, 716, long0, long1, (-1966), "q0no\"MvX", 1, true, 1);
      mala0.getAno_colecao();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      mala1.setMaterial("mX-7MpE]Fi!");
      mala0.isPremium();
      mala0.setValorizacao((-1749.1F));
      mala1.getValorizacao();
      mala1.isPremium();
      mala1.equals(mala0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.equals((Object) null);
      mala0.setValorizacao(0.0F);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setN_utilizadores(4121);
      mala0.getAno_colecao();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Double double0 = new Double(0.01);
      Long long0 = new Long(2844L);
      Mala mala0 = new Mala((String) null, (String) null, double0, false, 0, 480, long0, long0, (-1), "", 0, false, 0);
      mala0.getDimensao();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Double double0 = new Double((-3005.0));
      Long long0 = new Long(0);
      Long long1 = new Long(2674L);
      Mala mala0 = new Mala("kMoe*&qZ$", "kMoe*&qZ$", double0, false, 0, (-1785), long0, long1, (-1785), "", 0, true, 2674L);
      mala0.clone();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.toString();
      Mala mala1 = mala0.clone();
      mala1.setDescricao("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: false Estado de uso: -1 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Dimens\u00E3o: 0 Material:  Ano da Cole\u00E7\u00E3o: 0 Premium: false Valoriza\u00E7\u00E3o: 0.0}");
      mala0.setDimensao(10);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setPreco_base((-502));
      mala0.setMarca(" Marca: ");
      LocalDate localDate0 = MockLocalDate.ofYearDay((-502), 1);
      mala0.preco_atual(localDate0);
      mala0.setNovo(false);
      mala0.toString();
      mala0.getMaterial();
      mala0.setDisponivel(true);
      mala0.setPremium(true);
      mala0.preco_atual(localDate0);
      mala0.equals((Object) null);
      mala0.setDimensao(1);
      mala0.setMaterial("PgwO");
      mala0.isPremium();
      Object object0 = new Object();
      mala0.equals(object0);
      mala0.isPremium();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Double double0 = new Double((-1225.0294302));
      Long long0 = new Long(0L);
      Mala mala0 = new Mala((String) null, (String) null, double0, false, (-1048), 309, long0, long0, (-1048), (String) null, 0, false, 2405.0F);
      Artigo.criaCodigo();
      Mala mala1 = new Mala(mala0);
      mala1.setPreco_base(3L);
      Long.sum(3L, 0L);
      mala1.preco_atual((LocalDate) null);
      mala0.setValorizacao(2405.0F);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setEstado_uso(0);
      Month month0 = Month.FEBRUARY;
      LocalDate localDate0 = MockLocalDate.of(10, month0, 10);
      mala0.mostrar(localDate0);
      mala0.setMaterial("");
      mala0.isPremium();
      mala0.getValorizacao();
      mala0.toString();
      mala0.getMaterial();
      mala0.getDimensao();
      mala0.isPremium();
      mala0.setValorizacao(0.0F);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setDisponivel(false);
      mala0.isPremium();
      mala0.setDimensao(2820);
      mala0.setValorizacao((-3854.0955F));
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      mala0.preco_atual(localDate0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Mala mala0 = new Mala();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(2L);
      mala0.mostrar(localDate0);
      mala0.setN_utilizadores(0);
      mala0.setPreco_base(3167.84338);
      mala0.setDisponivel(false);
      mala0.setValorizacao(0.0F);
      mala0.isPremium();
      mala0.preco_atual(localDate0);
      mala0.getValorizacao();
      mala0.preco_atual(localDate0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      Artigo.setCodigo("");
      mala1.getDimensao();
      mala1.getValorizacao();
      String string0 = "rM$,706/lB^Zi_]H-0m";
      Double double0 = new Double(2L);
      Double.isFinite(0);
      Mala mala2 = null;
      try {
        mala2 = new Mala("rM$,706/lB^Zi_]H-0m", "rM$,706/lB^Zi_]H-0m", double0, true, 0, 182, (Long) 3L, (Long) null, 0, "", 0, true, 182);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Double double0 = new Double(1561.7930701532575);
      Long long0 = new Long(0L);
      Double.min(0.0, (-1958));
      Mala mala0 = new Mala("", (String) null, double0, true, (-1958), (-1958), long0, long0, 1, " Novo: ", 1, true, (-1958));
      mala0.getValorizacao();
      Object object0 = new Object();
      mala0.equals(object0);
      mala0.setMaterial("");
      LocalDate localDate0 = MockLocalDate.now();
      mala0.preco_atual(localDate0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.equals("");
      LocalDate localDate0 = mala0.getData_venda();
      mala0.preco_atual(localDate0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setValorizacao((-182.0F));
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setDimensao((-1));
      mala0.setVendedor((-1));
      mala0.setPremium(false);
      mala0.setPremium(false);
      LocalDate localDate0 = MockLocalDate.now();
      mala0.preco_atual(localDate0);
      Mala mala1 = new Mala(mala0);
      mala0.equals(mala1);
      mala1.setPremium(false);
      LocalDate localDate1 = MockLocalDate.from(localDate0);
      mala1.preco_atual(localDate1);
      mala1.setDisponivel(false);
      mala1.setDimensao(0);
      mala0.setPremium(true);
      mala0.setValorizacao(2L);
      mala0.getMaterial();
      mala0.isPremium();
      mala0.equals(mala1);
      mala0.toString();
      mala0.toString();
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setDimensao((-1));
      mala0.setVendedor((-1));
      mala0.isPremium();
      mala0.setPremium(false);
      mala0.setPremium(false);
      LocalDate localDate0 = MockLocalDate.now();
      mala0.preco_atual(localDate0);
      mala0.setDimensao(0);
      Mala mala1 = new Mala(mala0);
      mala0.equals(mala1);
      mala1.setPremium(false);
      LocalDate localDate1 = MockLocalDate.from(localDate0);
      mala1.preco_atual(localDate1);
      mala1.setDisponivel(false);
      mala1.setAno_colecao((-1));
      mala1.setDimensao(0);
      mala0.setValorizacao(2L);
      mala0.getMaterial();
      mala0.isPremium();
      mala0.equals(mala1);
      mala0.toString();
      mala0.toString();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Double double0 = new Double((-1.0));
      Long long0 = new Long((-4945));
      Long long1 = new Long(182);
      Long.compareUnsigned((-1006), 15L);
      Mala mala0 = new Mala("KybJ) eyaQ/nQY>7h4", " Dimens\u00E3o: ", double0, false, (-4945), 182, long0, long1, (-1006), " Dimens\u00E3o: ", 0, true, 0);
      Mala mala1 = new Mala(mala0);
      mala1.setMaterial("Z)s");
      Long.getLong(" Id da transportadora: ", (long) 182);
      mala1.getValorizacao();
      mala1.setPremium(true);
      mala0.getValorizacao();
      Double.min((-4945), 0.0);
      mala1.setDimensao((-4945));
      mala0.setPremium(false);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setPreco_base((-502));
      mala0.setMarca(" Marca: ");
      LocalDate localDate0 = MockLocalDate.ofYearDay((-502), 1);
      mala0.preco_atual(localDate0);
      mala0.setNovo(true);
      mala0.setData_venda(localDate0);
      mala0.toString();
      mala0.getMaterial();
      mala0.setDisponivel(true);
      mala0.setPremium(true);
      mala0.preco_atual(localDate0);
      mala0.equals((Object) null);
      mala0.setDimensao(1);
      mala0.setMaterial("PgwO");
      mala0.isPremium();
      Object object0 = new Object();
      mala0.equals(object0);
      mala0.isPremium();
      System.setCurrentTimeMillis(0L);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Double double0 = new Double(1187.5240337);
      Long long0 = new Long((-2299));
      Long long1 = new Long((-2461L));
      try { 
        Long.parseUnsignedLong("gL`2D~#r8>Vy`u5Q1");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"gL`2D~#r8>Vy`u5Q1\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      mala0.isPremium();
      mala0.setValorizacao((-1749.1F));
      mala1.getValorizacao();
      mala1.isPremium();
      mala1.equals(mala0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Double double0 = new Double(0L);
      Long long0 = new Long(0L);
      Long long1 = new Long(0L);
      Mala mala0 = new Mala("", "Q@", double0, true, 1, 4907, long0, long1, 13, "Q@", 1, false, 1.0F);
      mala0.equals("Q@");
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      mala1.setMaterial("A");
      mala0.isPremium();
      mala1.getValorizacao();
      mala1.isPremium();
      mala1.equals(mala0);
      mala0.toString();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Mala mala0 = new Mala();
      mala0.setDimensao((-1));
      mala0.setVendedor((-1));
      mala0.isPremium();
      mala0.setPremium(false);
      mala0.setPremium(true);
      LocalDate localDate0 = MockLocalDate.now();
      mala0.preco_atual(localDate0);
      mala0.setDimensao(0);
      Mala mala1 = new Mala();
      mala0.equals(mala1);
      LocalDate localDate1 = MockLocalDate.from(localDate0);
      mala1.preco_atual(localDate1);
      mala1.setDimensao(0);
      mala0.setPremium(true);
      mala0.setValorizacao(3L);
      mala0.getMaterial();
      mala0.isPremium();
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      mala1.equals(mala0);
      mala1.mostrar((LocalDate) null);
      mala0.setNovo(true);
      mala0.setCodigo_barras("Mek");
      mala1.setDisponivel(true);
      mala0.setAno_colecao(976);
      mala1.setDimensao(1805);
      Mala mala2 = mala0.clone();
      mala0.setN_utilizadores(2725);
      mala2.getValorizacao();
      mala2.setMaterial("sMn;9:D,6_;ME?P2j");
      mala2.toString();
      mala1.getMaterial();
      mala2.preco_atual((LocalDate) null);
      mala0.setMaterial("Mala:: {Artigo:: { C\u00F3digo de barras: Mek Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: true Estado de uso: -1 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Dimens\u00E3o: 0 Material: sMn;9:D,6_;ME?P2j Ano da Cole\u00E7\u00E3o: 976 Premium: false Valoriza\u00E7\u00E3o: 0.0}");
      mala0.setPremium(true);
      assertEquals("Mala:: {Artigo:: { C\u00F3digo de barras: Mek Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: true Estado de uso: -1 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Dimens\u00E3o: 0 Material: sMn;9:D,6_;ME?P2j Ano da Cole\u00E7\u00E3o: 976 Premium: false Valoriza\u00E7\u00E3o: 0.0}", mala0.getMaterial());
  }
}
