/*
 * This file was automatically generated by EvoSuite
 * Thu May 02 10:31:35 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.Clock;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Parsing_ESTest extends Parsing_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(0);
      Clock clock0 = MockClock.system(zoneOffset0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      String[] stringArray0 = new String[8];
      parsing0.venderTshit((-1L), localDate0, stringArray0);
      assertEquals(8, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      String[] stringArray0 = new String[9];
      parsing0.venderSapatilha(0L, localDate0, stringArray0);
      assertEquals(9, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      String[] stringArray0 = new String[9];
      parsing0.venderMala(0L, localDate0, stringArray0);
      assertEquals(9, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing((Vintage) null, menu0);
      Vintage vintage0 = parsing0.getVintage();
      assertNull(vintage0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      HashMap<Long, Utilizador> hashMap0 = new HashMap<Long, Utilizador>();
      HashMap<String, String> hashMap1 = new HashMap<String, String>();
      HashMap<String, Long> hashMap2 = new HashMap<String, Long>();
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores(hashMap0, hashMap1, hashMap2);
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Menu menu0 = new Menu();
      Vintage vintage0 = new Vintage(gestor_Artigos0, gestor_Utilizadores0, (GestorEncomendas) null, gestor_Transportadoras0, menu0);
      Parsing parsing0 = new Parsing(vintage0, menu0);
      Vintage vintage1 = parsing0.getVintage();
      assertSame(vintage1, vintage0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      HashMap<Long, Encomenda> hashMap1 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap1);
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Menu menu0 = new Menu();
      Vintage vintage0 = new Vintage(gestor_Artigos0, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, menu0, 2222);
      Parsing parsing0 = new Parsing(vintage0, menu0);
      Vintage vintage1 = parsing0.getVintage();
      assertEquals(2222L, vintage1.getUtilizador());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Parsing parsing0 = new Parsing((Vintage) null, (Menu) null);
      Menu menu0 = parsing0.getMenu();
      assertNull(menu0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[4];
      Vintage vintage0 = new Vintage();
      Parsing parsing0 = new Parsing(vintage0, (Menu) null);
      // Undeclared exception!
      try { 
        parsing0.venderTshit((-23), (LocalDate) null, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Parsing parsing0 = new Parsing(vintage0, (Menu) null);
      Period period0 = Period.ofWeeks(0);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      String[] stringArray0 = new String[6];
      // Undeclared exception!
      try { 
        parsing0.venderSapatilha((-1L), localDate0, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Parsing parsing0 = new Parsing((Vintage) null, (Menu) null);
      LocalDate localDate0 = MockLocalDate.now();
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        parsing0.venderMala(4315L, localDate0, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Menu menu0 = new Menu();
      LocalDate localDate0 = MockLocalDate.now();
      Parsing parsing0 = new Parsing((Vintage) null, menu0);
      // Undeclared exception!
      try { 
        parsing0.leitura_ficheiro("6;r{30BVQV\"|WJn r@", localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      String[] stringArray0 = new String[3];
      stringArray0[0] = "";
      // Undeclared exception!
      try { 
        parsing0.adicionar_comando(stringArray0, (LocalDate) null);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      LocalDate localDate0 = vintage0.getData();
      String[] stringArray0 = new String[5];
      // Undeclared exception!
      try { 
        parsing0.adicionar_comando(stringArray0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Vintage vintage0 = Vintage.load();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      String[] stringArray0 = new String[0];
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
      // Undeclared exception!
      try { 
        parsing0.adicionar_comando(stringArray0, localDate0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing((Vintage) null, menu0);
      parsing0.setMenu(menu0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      Vintage vintage1 = parsing0.getVintage();
      assertSame(vintage0, vintage1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      parsing0.setVintage(vintage0);
      assertEquals((-1L), vintage0.getUtilizador());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      Menu menu1 = parsing0.getMenu();
      assertSame(menu1, menu0);
  }
}
