/*
 * This file was automatically generated by EvoSuite
 * Thu May 02 18:53:47 GMT 2024
 */

package View;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Model.Artigo;
import Model.Encomenda;
import Model.TShirt;
import Model.Transportadoras;
import View.Output;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Output_ESTest extends Output_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Output output0 = new Output();
      String[] stringArray0 = new String[0];
      output0.printMenus(stringArray0, "Data de Lancamento: ", 0);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Output output0 = new Output();
      // Undeclared exception!
      try { 
        output0.printTransportadoras((Map<String, Transportadoras>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Output output0 = new Output();
      // Undeclared exception!
      try { 
        output0.printTop10((Map<String, Double>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Output output0 = new Output();
      // Undeclared exception!
      try { 
        output0.printEncomendas((List<Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Output output0 = new Output();
      // Undeclared exception!
      try { 
        output0.printCarrinho((List<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Output output0 = new Output();
      LinkedList<Artigo> linkedList0 = new LinkedList<Artigo>();
      linkedList0.add((Artigo) null);
      // Undeclared exception!
      try { 
        output0.printArtigos(linkedList0, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Output output0 = new Output();
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      Double double0 = new Double((-1.0));
      hashMap0.put("NORMAL", double0);
      output0.printTop10(hashMap0);
      assertEquals(1, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Output output0 = new Output();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer((-124));
      linkedList0.offerFirst(integer0);
      output0.printCarrinho(linkedList0);
      assertEquals(1, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Output output0 = new Output();
      LinkedList<Encomenda> linkedList0 = new LinkedList<Encomenda>();
      Encomenda encomenda0 = new Encomenda();
      linkedList0.add(encomenda0);
      output0.printEncomendas(linkedList0);
      assertTrue(linkedList0.contains(encomenda0));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Output output0 = new Output();
      LinkedList<Artigo> linkedList0 = new LinkedList<Artigo>();
      TShirt.Tamanho tShirt_Tamanho0 = TShirt.Tamanho.M;
      TShirt.Padrao tShirt_Padrao0 = TShirt.Padrao.LISO;
      Artigo.Estado artigo_Estado0 = Artigo.Estado.NOVO;
      Artigo.Avaliacao artigo_Avaliacao0 = Artigo.Avaliacao.SATISFATORIO;
      TShirt tShirt0 = new TShirt(tShirt_Tamanho0, tShirt_Padrao0, "hWrr|fo", artigo_Estado0, 1979, artigo_Avaliacao0, "hWrr|fo", "D|-J%$", "D|-J%$", 1979, 1979, "D|-J%$");
      linkedList0.add((Artigo) tShirt0);
      LocalDate localDate0 = MockLocalDate.now();
      output0.printArtigos(linkedList0, localDate0);
      assertEquals(1, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Output output0 = new Output();
      HashMap<String, Transportadoras> hashMap0 = new HashMap<String, Transportadoras>();
      Transportadoras transportadoras0 = new Transportadoras("NORMAL", (-124), (-124), true, (-2453.0343915));
      hashMap0.put("NORMAL", transportadoras0);
      output0.printTransportadoras(hashMap0);
      assertEquals(1, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Output output0 = new Output();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "NORMAL";
      output0.printMenus(stringArray0, "NORMAL", 0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Output output0 = new Output();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "hWrr|fo";
      stringArray0[1] = "hWrr|fo";
      stringArray0[2] = "hWrr|fo";
      stringArray0[3] = "D|-J%$";
      stringArray0[4] = "D|-J%$";
      stringArray0[5] = "+-----------------------------+";
      stringArray0[6] = "hWrr|fo";
      stringArray0[7] = "D|-J%$";
      stringArray0[8] = "hWrr|fo";
      output0.printMenus(stringArray0, "D|-J%$", 1979);
      assertEquals(9, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Output output0 = new Output();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "hWrr|fo";
      stringArray0[1] = "hWrr|fo";
      // Undeclared exception!
      try { 
        output0.printMenus(stringArray0, "D|-J%$", 1979);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Output output0 = new Output();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "NORMAL";
      output0.printMenus(stringArray0, "NORMAL", (-124));
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Output output0 = new Output();
      output0.printMessage("");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Output output0 = new Output();
      output0.formulasTransportadora();
  }
}
